### PR TITLE
Add target prop to Button

### PR DESCRIPTION
**Pull request by ellisjas**

### CODE REVIEW

**Comment by sentience** [comment]
Assuming this is to enable setting the `target` attribute to `_blank` to open links in a new tab/window, there is an accessibility impact to doing this that we'd ideally like to enforce with this component.

Check with @didoesdigital for our current approach to new-window links. In brief, Culture Amp should avoid creating new-window links unnecessarily, because they cause users of assistive technologies like screen readers to lose their place (because they can't hit the Back button in the new window to get back to where they just were). We should instead encourage users to choose for themselves when to open a link in a new window, using their browser's facility for this.

In exceptional situations where allowing the user to click a link could cause them to lose work (like if they're in the middle of completing a complex form and opening the link would throw away their unsubmitted responses), then we can use a new-window link; however, the link must be labelled a tooltip or other text that says “opens in a new window” or similar.

Given the above, ideally our Button component should not allow setting the `target` attribute directly, but instead should support a `newtab` prop or similar that not only sets `target=_blank`, but also attaches the required announcement text.

**Comment by ellisjas** [comment]
That can be done but that adds a layer of complexity involving where the tooltip should be positioned. This also wouldn't be straight-forward with the elm version of the button (or so I'm told).

**Comment by sentience** [comment]
@ellisjas I agree it's not easy. It's up to Design Systems team to decide how to handle this, but we need to have some strategy for avoiding teams unknowingly creating inaccessible new-window buttons in our platform.

**Pull request merged**
